server:
  port: 8004

api-gateway:
  address: http://link:8001
  groupId: 10001                  # 网关分组；每一个网关通信组件都分配一个对应的分组
  gatewayId: api-gateway-g4       # 网关标识；
  gatewayName: 电商配送网关         # 网关名称
  gatewayAddress: link:7397  # 网关服务；网关的通信服务Netty启动时使用IP和端口